### ISSUE TITLE
As a grant ship I want the project approval to show after I approve.

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#120] opened 2024-03-29 00:46 UTC
I reviewed and approved the project, but it still showed the review button after wards. Showed the next step after a refresh. 

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/4854ce09-c701-4dfb-8ad8-076ff311afe9)

**Comment by jordanlesich** [comment] 2024-04-25 02:06
Duplicate of https://github.com/DAOmasons/grant-ships-app/issues/122

**Closed by jordanlesich** 2024-04-25 02:06 UTC
Labels: duplicate
